# Metodología del Notebook 5 - Preparación de tablas finales y exportes

## Objetivo

El objetivo de este notebook es organizar y exportar los principales datasets agregados que servirán como base para el dashboard final y para la comunicación de resultados del proyecto. Esta fase no busca generar nuevos hallazgos, sino estructurar la información ya analizada en formatos claros, consistentes y reutilizables.

## Metodología

En este notebook se preparan las tablas finales del proyecto para su uso en visualización y comunicación de resultados. A partir de la base enriquecida con variables de negocio y sentimiento, se construyen indicadores agregados y tablas resumen orientadas al dashboard y a la presentación ejecutiva.

## Procedimiento

A partir de la base maestra enriquecida con variables de negocio, logística, geografía, categorías y sentimiento, se construyen tablas resumen con distintos niveles de agregación. Estas tablas incluyen KPIs generales del ecommerce, evolución temporal de pedidos y ventas, métricas logísticas, resultados por categoría, resultados por estado y distribución del sentimiento en las reseñas.

Posteriormente, cada tabla se exporta en formato CSV para facilitar su utilización en herramientas de visualización como Power BI, Tableau o similares. De este modo, el notebook actúa como puente entre la fase analítica y la fase de presentación ejecutiva del proyecto.

## Resultado esperado

El resultado final de este notebook es un conjunto de archivos limpios y estructurados, preparados para alimentar el dashboard y facilitar la elaboración de la memoria técnica y la presentación final.

In [103]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [104]:
df = pd.read_csv("../data/final/master_orders_with_sentiment.csv")
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_days,carrier_days,delay_days,is_late,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,n_items,n_products,n_sellers,total_price,total_freight,payment_count,payment_value_total,max_installments,review_score,review_creation_date,review_answer_timestamp,review_comment_title,review_comment_message,main_category,sentiment_5,sentiment_3,sentiment_confidence
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.00,0.00,2.00,-8.00,0.00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,"3,149.00",-23.58,-46.59,sao paulo,SP,1.00,1.00,1.00,29.99,8.72,3.00,38.71,1.00,4.00,2017-10-11 00:00:00,2017-10-12 03:43:48,NaN,"Não testei o produto ainda, mas ele veio corre...",housewares,Neutro,Neutro,0.53
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.00,1.00,1.00,-6.00,0.00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,"47,813.00",-12.18,-44.66,barreiras,BA,1.00,1.00,1.00,118.70,22.76,1.00,141.46,1.00,4.00,2018-08-08 00:00:00,2018-08-08 18:37:50,Muito boa a loja,Muito bom o produto.,perfumery,Muy positivo,Positivo,0.56
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.00,0.00,0.00,-18.00,0.00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,"75,265.00",-16.75,-48.51,vianopolis,GO,1.00,1.00,1.00,159.90,19.22,1.00,179.12,3.00,5.00,2018-08-18 00:00:00,2018-08-22 19:07:58,NaN,NaN,auto,NaN,NaN,NaN
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.00,0.00,3.00,-13.00,0.00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,"59,296.00",-5.77,-35.27,sao goncalo do amarante,RN,1.00,1.00,1.00,45.00,27.20,1.00,72.20,1.00,5.00,2017-12-03 00:00:00,2017-12-05 19:21:58,NaN,O produto foi exatamente o que eu esperava e e...,pet_shop,Muy positivo,Positivo,0.46
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.00,0.00,0.00,-10.00,0.00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,"9,195.00",-23.68,-46.51,santo andre,SP,1.00,1.00,1.00,19.90,8.72,1.00,28.62,1.00,5.00,2018-02-17 00:00:00,2018-02-18 13:02:51,NaN,NaN,stationery,NaN,NaN,NaN

In [105]:
df.shape

(99441, 39)

### Aseguramos el formato correcto de las fechas:

In [106]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

### Creamos variables temporales para el dashboard

In [107]:
df["purchase_year"] = df["order_purchase_timestamp"].dt.year
df["purchase_month"] = df["order_purchase_timestamp"].dt.month
df["purchase_month_name"] = df["order_purchase_timestamp"].dt.month_name()
df["purchase_year_month"] = df["order_purchase_timestamp"].dt.to_period("M").astype(str)

df[["order_purchase_timestamp", "purchase_year", "purchase_month", "purchase_year_month"]].head()

  order_purchase_timestamp  purchase_year  purchase_month purchase_year_month
0      2017-10-02 10:56:33           2017              10             2017-10
1      2018-07-24 20:41:37           2018               7             2018-07
2      2018-08-08 08:38:49           2018               8             2018-08
3      2017-11-18 19:28:06           2017              11             2017-11
4      2018-02-13 21:18:39           2018               2             2018-02

### Definición de los KPIs

In [108]:
kpis_dashboard = pd.DataFrame({
    "KPI": [
        "Total pedidos",
        "Clientes únicos",
        "Ventas totales (R$)",
        "Ticket promedio (R$)",
        "Review score promedio",
        "% pedidos tardíos",
        "% sentimiento positivo",
        "% sentimiento negativo",
        "% sentimiento neutro"
    ],
    "Valor": [
        len(df),
        df["customer_unique_id"].nunique(),
        round(df["payment_value_total"].sum(), 2),
        round(df["payment_value_total"].mean(), 2),
        round(df["review_score"].mean(), 2),
        round(df["is_late"].mean() * 100, 2),
        round((df["sentiment_3"] == "Positivo").mean() * 100, 2),
        round((df["sentiment_3"] == "Negativo").mean() * 100, 2),
        round((df["sentiment_3"] == "Neutro").mean() * 100, 2)
    ]
}).reset_index(drop=True)

kpis_dashboard

                      KPI         Valor
0           Total pedidos     99,441.00
1         Clientes únicos     96,096.00
2     Ventas totales (R$) 16,008,872.12
3    Ticket promedio (R$)        160.99
4   Review score promedio          4.09
5       % pedidos tardíos          6.77
6  % sentimiento positivo         21.74
7  % sentimiento negativo         15.57
8    % sentimiento neutro          3.73

### Evolución mensual

In [109]:
monthly_dashboard = (
    df
    .groupby("purchase_year_month", as_index=False)
    .agg(
        pedidos=("order_id", "count"),
        ventas=("payment_value_total", "sum"),
        ticket_promedio=("payment_value_total", "mean"),
        review_score_promedio=("review_score", "mean"),
        porcentaje_tardios=("is_late", "mean")
    )
)

monthly_dashboard["ventas"] = monthly_dashboard["ventas"].round(2)
monthly_dashboard["ticket_promedio"] = monthly_dashboard["ticket_promedio"].round(2)
monthly_dashboard["review_score_promedio"] = monthly_dashboard["review_score_promedio"].round(2)
monthly_dashboard["porcentaje_tardios"] = (monthly_dashboard["porcentaje_tardios"] * 100).round(2)

monthly_dashboard = monthly_dashboard.sort_values("purchase_year_month").reset_index(drop=True)
monthly_dashboard.head()

,purchase_year_month,pedidos,ventas,ticket_promedio,review_score_promedio,porcentaje_tardios
0,2016-09,4,252.24,84.08,1.00,100.00
1,2016-10,324,"59,090.48",182.38,3.56,0.74
2,2016-12,1,19.62,19.62,5.00,0.00
3,2017-01,800,"138,488.04",173.11,4.06,2.93
4,2017-02,1780,"291,908.01",163.99,4.02,2.96

### Creación de categorias

In [110]:
category_df = df[df["main_category"].notna()].copy()
category_df = category_df[category_df["main_category"] != "Unknown"]

category_dashboard = (
    category_df
    .groupby("main_category", as_index=False)
    .agg(
        pedidos=("order_id", "count"),
        ventas=("payment_value_total", "sum"),
        ticket_promedio=("payment_value_total", "mean"),
        review_score_promedio=("review_score", "mean"),
        porcentaje_tardios=("is_late", "mean")
    )
)

category_dashboard["ventas"] = category_dashboard["ventas"].round(2)
category_dashboard["ticket_promedio"] = category_dashboard["ticket_promedio"].round(2)
category_dashboard["review_score_promedio"] = category_dashboard["review_score_promedio"].round(2)
category_dashboard["porcentaje_tardios"] = (category_dashboard["porcentaje_tardios"] * 100).round(2)

category_dashboard = category_dashboard.sort_values("ventas", ascending=False).reset_index(drop=True)
category_dashboard.head(10)

,main_category,pedidos,ventas,ticket_promedio,review_score_promedio,porcentaje_tardios
0,health_beauty,8810,"1,443,182.68",163.83,4.18,7.54
1,watches_gifts,5584,"1,299,139.04",232.65,4.07,7.45
2,bed_bath_table,9385,"1,257,907.93",134.03,3.97,7.46
3,sports_leisure,7668,"1,154,092.27",150.51,4.18,6.59
4,computers_accessories,6679,"1,063,925.67",159.29,4.03,6.40
5,furniture_decor,6350,"907,045.66",142.84,4.02,7.18
6,housewares,5812,"775,139.40",133.37,4.15,5.43
7,cool_stuff,3589,"716,406.30",199.61,4.19,5.94
8,auto,3891,"687,648.92",176.73,4.09,7.31
9,garden_tools,3479,"583,237.30",167.65,4.15,6.60

### Distribución Geografica

In [111]:
state_dashboard = (
    df
    .groupby("geolocation_state", as_index=False)
    .agg(
        pedidos=("order_id", "count"),
        ventas=("payment_value_total", "sum"),
        ticket_promedio=("payment_value_total", "mean"),
        review_score_promedio=("review_score", "mean"),
        porcentaje_tardios=("is_late", "mean")
    )
)

state_dashboard["ventas"] = state_dashboard["ventas"].round(2)
state_dashboard["ticket_promedio"] = state_dashboard["ticket_promedio"].round(2)
state_dashboard["review_score_promedio"] = state_dashboard["review_score_promedio"].round(2)
state_dashboard["porcentaje_tardios"] = (state_dashboard["porcentaje_tardios"] * 100).round(2)

state_dashboard = state_dashboard.sort_values("ventas", ascending=False).reset_index(drop=True)
state_dashboard.head(10)

,geolocation_state,pedidos,ventas,ticket_promedio,review_score_promedio,porcentaje_tardios
0,SP,41731,"5,996,050.41",143.69,4.17,4.49
1,RJ,12839,"2,142,349.25",166.86,3.88,12.12
2,MG,11624,"1,871,072.52",160.97,4.14,4.57
3,RS,5462,"890,584.82",163.05,4.13,6.07
4,PR,5034,"810,280.15",160.96,4.18,4.01
5,SC,3637,"623,086.43",171.32,4.07,8.20
6,BA,3371,"615,203.62",182.50,3.86,12.10
7,GO,2011,"349,377.13",173.73,4.04,6.57
8,DF,1969,"326,095.81",165.61,4.07,5.74
9,ES,2027,"325,490.67",160.58,4.04,10.61

## Analisis logistico

In [112]:
delivered_df = df[df["order_status"] == "delivered"].copy()

logistics_dashboard = pd.DataFrame({
    "KPI": [
        "Pedidos entregados",
        "Tiempo entrega promedio (días)",
        "Mediana entrega (días)",
        "Retraso promedio (días)",
        "% pedidos tardíos entregados"
    ],
    "Valor": [
        len(delivered_df),
        round(delivered_df["delivery_days"].mean(), 2),
        round(delivered_df["delivery_days"].median(), 2),
        round(delivered_df["delay_days"].mean(), 2),
        round(delivered_df["is_late"].mean() * 100, 2)
    ]
})

logistics_dashboard

                              KPI     Valor
0              Pedidos entregados 96,478.00
1  Tiempo entrega promedio (días)     12.09
2          Mediana entrega (días)     10.00
3         Retraso promedio (días)    -11.88
4    % pedidos tardíos entregados      6.77

## Analisis de sentimiento

In [113]:
sentiment_dashboard = (
    df[df["sentiment_3"].notna()]["sentiment_3"]
    .value_counts()
    .rename_axis("Sentimiento")
    .reset_index(name="Cantidad")
)

sentiment_dashboard["Porcentaje"] = (
    sentiment_dashboard["Cantidad"] / sentiment_dashboard["Cantidad"].sum() * 100
).round(2)

sentiment_dashboard = sentiment_dashboard.reset_index(drop=True)
sentiment_dashboard

  Sentimiento  Cantidad  Porcentaje
0    Positivo     21615       52.97
1    Negativo     15484       37.94
2      Neutro      3710        9.09

## Sentimientos por categoria

In [114]:
sentiment_category_df = df[
    df["main_category"].notna() &
    (df["main_category"] != "Unknown") &
    df["sentiment_3"].notna()
].copy()

sentiment_category_dashboard = (
    sentiment_category_df
    .groupby("main_category", as_index=False)["sentiment_3"]
    .value_counts(normalize=True)
)

sentiment_category_dashboard["proportion"] = (
    sentiment_category_dashboard["proportion"] * 100
).round(2)

sentiment_category_dashboard = sentiment_category_dashboard.reset_index(drop=True)
sentiment_category_dashboard.head(20)

                 main_category sentiment_3  proportion
0   agro_industry_and_commerce    Positivo       47.46
1   agro_industry_and_commerce    Negativo       44.07
2   agro_industry_and_commerce      Neutro        8.47
3             air_conditioning    Negativo       42.72
4             air_conditioning    Positivo       42.72
5             air_conditioning      Neutro       14.56
6                          art    Positivo       46.51
7                          art    Negativo       36.05
8                          art      Neutro       17.44
9        arts_and_craftmanship    Negativo       45.45
10       arts_and_craftmanship    Positivo       45.45
11       arts_and_craftmanship      Neutro        9.09
12                       audio    Positivo       47.44
13                       audio    Negativo       42.31
14                       audio      Neutro       10.26
15                        auto    Positivo       55.02
16                        auto    Negativo       36.19
17                        auto      Neutro        8.79
18                        baby    Positivo       50.66
19                        baby    Negativo       39.92

## Sentimiendo por geolocalizacion:

In [115]:
sentiment_category_pivot_dashboard = sentiment_category_dashboard.pivot(
    index="main_category",
    columns="sentiment_3",
    values="proportion"
).fillna(0).reset_index()

sentiment_category_pivot_dashboard.head(10)

sentiment_3               main_category  Negativo  Neutro  Positivo
0            agro_industry_and_commerce     44.07    8.47     47.46
1                      air_conditioning     42.72   14.56     42.72
2                                   art     36.05   17.44     46.51
3                 arts_and_craftmanship     45.45    9.09     45.45
4                                 audio     42.31   10.26     47.44
5                                  auto     36.19    8.79     55.02
6                                  baby     39.92    9.42     50.66
7                        bed_bath_table     38.42   10.01     51.57
8                books_general_interest     24.22    6.83     68.94
9                        books_imported     40.00   13.33     46.67

## Sentimientos por Estados

In [116]:
sentiment_state_df = df[
    df["geolocation_state"].notna() &
    df["sentiment_3"].notna()
].copy()

sentiment_state_dashboard = (
    sentiment_state_df
    .groupby("geolocation_state", as_index=False)["sentiment_3"]
    .value_counts(normalize=True)
)

sentiment_state_dashboard["proportion"] = (
    sentiment_state_dashboard["proportion"] * 100
).round(2)

sentiment_state_dashboard = sentiment_state_dashboard.reset_index(drop=True)
sentiment_state_dashboard.head(20)

   geolocation_state sentiment_3  proportion
0                 AC    Positivo       50.00
1                 AC    Negativo       44.74
2                 AC      Neutro        5.26
3                 AL    Negativo       51.50
4                 AL    Positivo       39.00
5                 AL      Neutro        9.50
6                 AM    Positivo       61.90
7                 AM    Negativo       31.75
8                 AM      Neutro        6.35
9                 AP    Positivo       70.00
10                AP    Negativo       23.33
11                AP      Neutro        6.67
12                BA    Positivo       50.42
13                BA    Negativo       39.96
14                BA      Neutro        9.61
15                CE    Positivo       51.99
16                CE    Negativo       39.11
17                CE      Neutro        8.90
18                DF    Positivo       51.60
19                DF    Negativo       40.23

In [117]:
sentiment_state_pivot_dashboard = sentiment_state_dashboard.pivot(
    index="geolocation_state",
    columns="sentiment_3",
    values="proportion"
).fillna(0).reset_index()

sentiment_state_pivot_dashboard.head(20)

sentiment_3 geolocation_state  Negativo  Neutro  Positivo
0                          AC     44.74    5.26     50.00
1                          AL     51.50    9.50     39.00
2                          AM     31.75    6.35     61.90
3                          AP     23.33    6.67     70.00
4                          BA     39.96    9.61     50.42
5                          CE     39.11    8.90     51.99
6                          DF     40.23    8.17     51.60
7                          ES     35.64   11.02     53.34
8                          GO     36.39    9.27     54.34
9                          MA     41.45    9.86     48.70
10                         MG     35.40    8.75     55.84
11                         MS     34.34    8.08     57.58
12                         MT     35.47    9.61     54.93
13                         PA     40.34    9.98     49.68
14                         PB     42.34    8.87     48.79
15                         PE     37.68    8.87     53.45
16                         PI     34.38    6.25     59.38
17                         PR     37.11    8.76     54.14
18                         RJ     44.71    8.51     46.78
19                         RN     39.34    7.11     53.55

## Clientes existentes con indicadores clave

In [118]:
customer_dashboard = (
    df
    .groupby("customer_unique_id", as_index=False)
    .agg(
        total_pedidos=("order_id", "count"),
        gasto_total=("payment_value_total", "sum"),
        ticket_promedio=("payment_value_total", "mean"),
        review_score_promedio=("review_score", "mean")
    )
)

customer_dashboard["segmento_frecuencia"] = np.where(
    customer_dashboard["total_pedidos"] == 1,
    "Compra única",
    "Cliente repetidor"
)

customer_dashboard["gasto_total"] = customer_dashboard["gasto_total"].round(2)
customer_dashboard["ticket_promedio"] = customer_dashboard["ticket_promedio"].round(2)
customer_dashboard["review_score_promedio"] = customer_dashboard["review_score_promedio"].round(2)

customer_dashboard.head()

,customer_unique_id,total_pedidos,gasto_total,ticket_promedio,review_score_promedio,segmento_frecuencia
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,141.90,5.00,Compra única
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,27.19,4.00,Compra única
2,0000f46a3911fa3c0805444483337064,1,86.22,86.22,3.00,Compra única
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,43.62,4.00,Compra única
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,196.89,5.00,Compra única

## Resumen de clientes para el dashboard

In [119]:
customer_segment_dashboard = (
    customer_dashboard
    .groupby("segmento_frecuencia", as_index=False)
    .agg(
        clientes=("customer_unique_id", "count"),
        gasto_total_promedio=("gasto_total", "mean"),
        ticket_promedio_cliente=("ticket_promedio", "mean"),
        review_score_promedio=("review_score_promedio", "mean")
    )
)

customer_segment_dashboard["gasto_total_promedio"] = customer_segment_dashboard["gasto_total_promedio"].round(2)
customer_segment_dashboard["ticket_promedio_cliente"] = customer_segment_dashboard["ticket_promedio_cliente"].round(2)
customer_segment_dashboard["review_score_promedio"] = customer_segment_dashboard["review_score_promedio"].round(2)

customer_segment_dashboard = customer_segment_dashboard.reset_index(drop=True)
customer_segment_dashboard

,segmento_frecuencia,clientes,gasto_total_promedio,ticket_promedio_cliente,review_score_promedio
0,Cliente repetidor,2997,314.99,148.50,4.12
1,Compra única,93099,161.82,161.82,4.08

In [120]:
kpis_dashboard.to_csv("../outputs/dashboard/kpis_dashboard.csv", index=False)
monthly_dashboard.to_csv("../outputs/dashboard/monthly_dashboard.csv", index=False)
category_dashboard.to_csv("../outputs/dashboard/category_dashboard.csv", index=False)
state_dashboard.to_csv("../outputs/dashboard/state_dashboard.csv", index=False)
logistics_dashboard.to_csv("../outputs/dashboard/logistics_dashboard.csv", index=False)
sentiment_dashboard.to_csv("../outputs/dashboard/sentiment_dashboard.csv", index=False)
customer_dashboard.to_csv("../outputs/dashboard/customer_dashboard.csv", index=False)
customer_segment_dashboard.to_csv("../outputs/dashboard/customer_segment_dashboard.csv", index=False)

sentiment_category_pivot_dashboard.to_csv("../outputs/dashboard/sentiment_category_pivot_dashboard.csv", index=False)
sentiment_state_pivot_dashboard.to_csv("../outputs/dashboard/sentiment_state_pivot_dashboard.csv", index=False)

In [121]:
import os

sorted(os.listdir("../outputs/dashboard"))

['.DS_Store',
 'category_dashboard.csv',
 'customer_dashboard.csv',
 'customer_segment_dashboard.csv',
 'kpis_dashboard.csv',
 'logistics_dashboard.csv',
 'monthly_dashboard.csv',
 'sentiment_category_pivot_dashboard.csv',
 'sentiment_dashboard.csv',
 'sentiment_state_pivot_dashboard.csv',
 'state_dashboard.csv']

In [122]:
from pathlib import Path

out = Path("outputs/dashboard")
out.mkdir(parents=True, exist_ok=True)

In [123]:
def exportar_tablas_looker(tablas, carpeta_salida):
    exportadas = []

    for nombre, df in tablas.items():
        archivo = carpeta_salida / f"{nombre}.xlsx"
        df.to_excel(archivo, index=False)
        exportadas.append(archivo.name)

    return exportadas

In [124]:
tablas_looker = {
    "01_kpis_dashboard": kpis_dashboard,
    "02_monthly_dashboard": monthly_dashboard,
    "03_category_dashboard": category_dashboard,
    "04_state_dashboard": state_dashboard,
    "05_customer_segment_dashboard": customer_segment_dashboard,
    "06_sentiment_dashboard": sentiment_dashboard,
    "07_sentiment_category_dashboard": sentiment_category_dashboard,
    "08_sentiment_state_dashboard": sentiment_state_dashboard
}

In [125]:
archivos_exportados = exportar_tablas_looker(tablas_looker, out)
archivos_exportados

['01_kpis_dashboard.xlsx',
 '02_monthly_dashboard.xlsx',
 '03_category_dashboard.xlsx',
 '04_state_dashboard.xlsx',
 '05_customer_segment_dashboard.xlsx',
 '06_sentiment_dashboard.xlsx',
 '07_sentiment_category_dashboard.xlsx',
 '08_sentiment_state_dashboard.xlsx']

In [126]:
list(out.glob("*.xlsx"))

[PosixPath('outputs/dashboard/~$01_kpis_dashboard.xlsx'),
 PosixPath('outputs/dashboard/03_category_dashboard.xlsx'),
 PosixPath('outputs/dashboard/04_state_dashboard.xlsx'),
 PosixPath('outputs/dashboard/01_kpis_dashboard.xlsx'),
 PosixPath('outputs/dashboard/00_kpis_dashboard_wide.xlsx'),
 PosixPath('outputs/dashboard/06_sentiment_dashboard.xlsx'),
 PosixPath('outputs/dashboard/08_sentiment_state_dashboard.xlsx'),
 PosixPath('outputs/dashboard/07_sentiment_category_dashboard.xlsx'),
 PosixPath('outputs/dashboard/02_monthly_dashboard.xlsx'),
 PosixPath('outputs/dashboard/05_customer_segment_dashboard.xlsx')]

In [132]:
kpis_dashboard_wide = (
    kpis_dashboard
    .set_index("KPI")["Valor"]
    .to_frame()
    .T
    .rename(columns={
        "Total pedidos": "total_pedidos",
        "Clientes únicos": "clientes_unicos",
        "Ventas totales (R$)": "ventas_totales",
        "Ticket promedio (R$)": "ticket_promedio",
        "Review score promedio": "review_score_promedio",
        "% pedidos tardíos": "porcentaje_tardios",
        "% sentimiento positivo": "porcentaje_sentimiento_positivo",
        "% sentimiento negativo": "porcentaje_sentimiento_negativo",
        "% sentimiento neutro": "porcentaje_sentimiento_neutro"
    })
)

kpis_dashboard_wide.columns.name = None

kpis_dashboard_wide
kpis_dashboard_wide.index = [0]
kpis_dashboard_wide.index.name = None
kpis_dashboard_wide.columns.name = None

kpis_dashboard_wide

,total_pedidos,clientes_unicos,ventas_totales,ticket_promedio,review_score_promedio,porcentaje_tardios,porcentaje_sentimiento_positivo,porcentaje_sentimiento_negativo,porcentaje_sentimiento_neutro
0,"99,441.00","96,096.00","16,008,872.12",160.99,4.09,6.77,21.74,15.57,3.73

In [128]:
kpis_dashboard_wide.to_excel(out / "00_kpis_dashboard_wide.xlsx", index=False)

In [129]:
kpis_dashboard["KPI"].tolist()

['Total pedidos',
 'Clientes únicos',
 'Ventas totales (R$)',
 'Ticket promedio (R$)',
 'Review score promedio',
 '% pedidos tardíos',
 '% sentimiento positivo',
 '% sentimiento negativo',
 '% sentimiento neutro']

# Conclusión del Notebook 5

En esta fase final se prepararon y exportaron las principales tablas agregadas del proyecto con el fin de facilitar la construcción del dashboard y la comunicación ejecutiva de resultados. A partir de la base enriquecida con información de negocio y sentimiento, se organizaron datasets específicos para KPIs generales, evolución temporal, categorías, geografía, logística, clientes y sentimiento.

El resultado de este notebook es un conjunto de archivos estructurados y listos para ser utilizados en herramientas de visualización, así como una base ordenada para la elaboración de la memoria técnica y la presentación final del proyecto.

kpis_dashboard.to_excel(out / "kpis_dashboard.xlsx", index=False)
monthly_dashboard.to_excel(out / "monthly_dashboard.xlsx", index=False)
category_dashboard.to_excel(out / "category_dashboard.xlsx", index=False)
state_dashboard.to_excel(out / "state_dashboard.xlsx", index=False)
customer_segment_dashboard.to_excel(out / "customer_segment_dashboard.xlsx", index=False)
sentiment_dashboard.to_excel(out / "sentiment_dashboard.xlsx", index=False)
sentiment_category_dashboard.to_excel(out / "sentiment_category_dashboard.xlsx", index=False)
sentiment_state_dashboard.to_excel(out / "sentiment_state_dashboard.xlsx", index=False)
list(out.glob("*.xlsx"))